package com.example.Employee.Management.System.personDetails.personCommon;

public enum Country {
    AFGHANISTAN("Afghanistan", "AF", "Asia", "Pashto, Dari"),
    ALBANIA("Albania", "AL", "Europe", "Albanian"),
    ALGERIA("Algeria", "DZ", "Africa", "Arabic, Tamazight"),
    ANDORRA("Andorra", "AD", "Europe", "Catalan"),
    ANGOLA("Angola", "AO", "Africa", "Portuguese"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "AG", "North America", "English"),
    ARGENTINA("Argentina", "AR", "South America", "Spanish"),
    ARMENIA("Armenia", "AM", "Asia", "Armenian"),
    AUSTRALIA("Australia", "AU", "Oceania", "English"),
    AUSTRIA("Austria", "AT", "Europe", "German"),
    AZERBAIJAN("Azerbaijan", "AZ", "Asia", "Azerbaijani"),
    BAHAMAS("Bahamas", "BS", "North America", "English"),
    BAHRAIN("Bahrain", "BH", "Asia", "Arabic"),
    BANGLADESH("Bangladesh", "BD", "Asia", "Bengali"),
    BARBADOS("Barbados", "BB", "North America", "English"),
    BELARUS("Belarus", "BY", "Europe", "Belarusian, Russian"),
    BELGIUM("Belgium", "BE", "Europe", "Dutch, French, German"),
    BELIZE("Belize", "BZ", "North America", "English"),
    BENIN("Benin", "BJ", "Africa", "French"),
    BHUTAN("Bhutan", "BT", "Asia", "Dzongkha"),
    BOLIVIA("Bolivia (Plurinational State of)", "BO", "South America", "Spanish"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "BA", "Europe", "Bosnian, Croatian, Serbian"),
    BOTSWANA("Botswana", "BW", "Africa", "English, Tswana"),
    BRAZIL("Brazil", "BR", "South America", "Portuguese"),
    BRUNEI_DARUSSALAM("Brunei Darussalam", "BN", "Asia", "Malay"),
    BULGARIA("Bulgaria", "BG", "Europe", "Bulgarian"),
    BURKINA_FASO("Burkina Faso", "BF", "Africa", "French"),
    BURUNDI("Burundi", "BI", "Africa", "Kirundi, French"),
    CABO_VERDE("Cabo Verde", "CV", "Africa", "Portuguese"),
    CAMBODIA("Cambodia", "KH", "Asia", "Khmer"),
    CAMEROON("Cameroon", "CM", "Africa", "French, English"),
    CANADA("Canada", "CA", "North America", "English, French"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "CF", "Africa", "French, Sango"),
    CHAD("Chad", "TD", "Africa", "French, Arabic"),
    CHILE("Chile", "CL", "South America", "Spanish"),
    CHINA("China", "CN", "Asia", "Mandarin"),
    COLOMBIA("Colombia", "CO", "South America", "Spanish"),
    COMOROS("Comoros", "KM", "Africa", "Comorian, Arabic, French"),
    CONGO("Congo", "CG", "Africa", "French"),
    COSTA_RICA("Costa Rica", "CR", "North America", "Spanish"),
    CROATIA("Croatia", "HR", "Europe", "Croatian"),
    CUBA("Cuba", "CU", "North America", "Spanish"),
    CYPRUS("Cyprus", "CY", "Asia", "Greek, Turkish"),
    CZECH_REPUBLIC("Czech Republic", "CZ", "Europe", "Czech"),
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO("Democratic Republic of the Congo", "CD", "Africa", "French"),
    DENMARK("Denmark", "DK", "Europe", "Danish"),
    DJIBOUTI("Djibouti", "DJ", "Africa", "French, Arabic"),
    DOMINICA("Dominica", "DM", "North America", "English"),
    DOMINICAN_REPUBLIC("Dominican Republic", "DO", "North America", "Spanish"),
    ECUADOR("Ecuador", "EC", "South America", "Spanish"),
    EGYPT("Egypt", "EG", "Africa", "Arabic"),
    EL_SALVADOR("El Salvador", "SV", "North America", "Spanish"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "GQ", "Africa", "Spanish, French, Portuguese"),
    ERITREA("Eritrea", "ER", "Africa", "Tigrinya, Arabic, English"),
    ESTONIA("Estonia", "EE", "Europe", "Estonian"),
    ESWATINI("Eswatini", "SZ", "Africa", "Swazi, English"),
    ETHIOPIA("Ethiopia", "ET", "Africa", "Amharic"),
    FIJI("Fiji", "FJ", "Oceania", "English, Fijian, Hindi"),
    FINLAND("Finland", "FI", "Europe", "Finnish, Swedish"),
    FRANCE("France", "FR", "Europe", "French"),
    GABON("Gabon", "GA", "Africa", "French"),
    GAMBIA("Gambia", "GM", "Africa", "English"),
    GEORGIA("Georgia", "GE", "Asia", "Georgian"),
    GERMANY("Germany", "DE", "Europe", "German"),
    GHANA("Ghana", "GH", "Africa", "English"),
    GREECE("Greece", "GR", "Europe", "Greek"),
    GRENADA("Grenada", "GD", "North America", "English"),
    GUATEMALA("Guatemala", "GT", "North America", "Spanish"),
    GUINEA("Guinea", "GN", "Africa", "French"),
    GUINEA_BISSAU("Guinea-Bissau", "GW", "Africa", "Portuguese"),
    GUYANA("Guyana", "GY", "South America", "English"),
    HAITI("Haiti", "HT", "North America", "French, Haitian Creole"),
    HONDURAS("Honduras", "HN", "North America", "Spanish"),
    HUNGARY("Hungary", "HU", "Europe", "Hungarian"),
    ICELAND("Iceland", "IS", "Europe", "Icelandic"),
    INDIA("India", "IN", "Asia", "Hindi, English"),
    INDONESIA("Indonesia", "ID", "Asia", "Indonesian"),
    IRAN_ISLAMIC_REPUBLIC_OF("Iran (Islamic Republic of)", "IR", "Asia", "Persian"),
    IRAQ("Iraq", "IQ", "Asia", "Arabic, Kurdish"),
    IRELAND("Ireland", "IE", "Europe", "Irish, English"),
    ISRAEL("Israel", "IL", "Asia", "Hebrew"),
    ITALY("Italy", "IT", "Europe", "Italian"),
    JAMAICA("Jamaica", "JM", "North America", "English"),
    JAPAN("Japan", "JP", "Asia", "Japanese"),
    JORDAN("Jordan", "JO", "Asia", "Arabic"),
    KAZAKHSTAN("Kazakhstan", "KZ", "Asia", "Kazakh, Russian"),
    KENYA("Kenya", "KE", "Africa", "English, Swahili"),
    KIRIBATI("Kiribati", "KI", "Oceania", "English, Kiribati"),
    KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF("Korea (Democratic People's Republic of)", "KP", "Asia", "Korean"),
    KOREA_REPUBLIC_OF("Korea, Republic of", "KR", "Asia", "Korean"),
    KUWAIT("Kuwait", "KW", "Asia", "Arabic"),
    KYRGYZSTAN("Kyrgyzstan", "KG", "Asia", "Kyrgyz, Russian"),
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC("Lao People's Democratic Republic", "LA", "Asia", "Lao"),
    LATVIA("Latvia", "LV", "Europe", "Latvian"),
    LEBANON("Lebanon", "LB", "Asia", "Arabic"),
    LESOTHO("Lesotho", "LS", "Africa", "English, Sesotho"),
    LIBERIA("Liberia", "LR", "Africa", "English"),
    LIBYA("Libya", "LY", "Africa", "Arabic"),
    LIECHTENSTEIN("Liechtenstein", "LI", "Europe", "German"),
    LITHUANIA("Lithuania", "LT", "Europe", "Lithuanian"),
    LUXEMBOURG("Luxembourg", "LU", "Europe", "French, German, Luxembourgish"),
    MADAGASCAR("Madagascar", "MG", "Africa", "Malagasy, French"),
    MALAWI("Malawi", "MW", "Africa", "English, Chewa"),
    MALAYSIA("Malaysia", "MY", "Asia", "Malay"),
    MALDIVES("Maldives", "MV", "Asia", "Dhivehi"),
    MALI("Mali", "ML", "Africa", "French"),
    MALTA("Malta", "MT", "Europe", "Maltese, English"),
    MARSHALL_ISLANDS("Marshall Islands", "MH", "Oceania", "Marshallese, English"),
    MAURITANIA("Mauritania", "MR", "Africa", "Arabic"),
    MAURITIUS("Mauritius", "MU", "Africa", "English, French, Mauritian Creole"),
    MEXICO("Mexico", "MX", "North America", "Spanish"),
    MICRONESIA_FEDERATED_STATES_OF("Micronesia (Federated States of)", "FM", "Oceania", "English"),
    MOLDOVA_REPUBLIC_OF("Moldova, Republic of", "MD", "Europe", "Moldovan, Romanian, Russian"),
    MONACO("Monaco", "MC", "Europe", "French"),
    MONGOLIA("Mongolia", "MN", "Asia", "Mongolian"),
    MONTENEGRO("Montenegro", "ME", "Europe", "Serbian"),
    MOROCCO("Morocco", "MA", "Africa", "Arabic"),
    MOZAMBIQUE("Mozambique", "MZ", "Africa", "Portuguese"),
    MYANMAR("Myanmar", "MM", "Asia", "Burmese"),
    NAMIBIA("Namibia", "NA", "Africa", "English, Afrikaans, German"),
    NAURU("Nauru", "NR", "Oceania", "Nauruan, English"),
    NEPAL("Nepal", "NP", "Asia", "Nepali"),
    NETHERLANDS("Netherlands", "NL", "Europe", "Dutch"),
    NEW_ZEALAND("New Zealand", "NZ", "Oceania", "English, Maori"),
    NICARAGUA("Nicaragua", "NI", "North America", "Spanish"),
    NIGER("Niger", "NE", "Africa", "French"),
    NIGERIA("Nigeria", "NG", "Africa", "English"),
    NORTH_MACEDONIA("North Macedonia", "MK", "Europe", "Macedonian"),
    NORWAY("Norway", "NO", "Europe", "Norwegian"),
    OMAN("Oman", "OM", "Asia", "Arabic"),
    PAKISTAN("Pakistan", "PK", "Asia", "Urdu, English"),
    PALAU("Palau", "PW", "Oceania", "Palauan, English"),
    PANAMA("Panama", "PA", "North America", "Spanish"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "PG", "Oceania", "English, Hiri Motu, Tok Pisin"),
    PARAGUAY("Paraguay", "PY", "South America", "Spanish, Guarani"),
    PERU("Peru", "PE", "South America", "Spanish"),
    PHILIPPINES("Philippines", "PH", "Asia", "Filipino, English"),
    POLAND("Poland", "PL", "Europe", "Polish"),
    PORTUGAL("Portugal", "PT", "Europe", "Portuguese"),
    QATAR("Qatar", "QA", "Asia", "Arabic"),
    ROMANIA("Romania", "RO", "Europe", "Romanian"),
    RUSSIAN_FEDERATION("Russian Federation", "RU", "Europe", "Russian"),
    RWANDA("Rwanda", "RW", "Africa", "Kinyarwanda, French, English"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "KN", "North America", "English"),
    SAINT_LUCIA("Saint Lucia", "LC", "North America", "English"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "VC", "North America", "English"),
    SAMOA("Samoa", "WS", "Oceania", "Samoan, English"),
    SAN_MARINO("San Marino", "SM", "Europe", "Italian"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "ST", "Africa", "Portuguese"),
    SAUDI_ARABIA("Saudi Arabia", "SA", "Asia", "Arabic"),
    SENEGAL("Senegal", "SN", "Africa", "French"),
    SERBIA("Serbia", "RS", "Europe", "Serbian"),
    SEYCHELLES("Seychelles", "SC", "Africa", "Seychellois Creole, English, French"),
    SIERRA_LEONE("Sierra Leone", "SL", "Africa", "English"),
    SINGAPORE("Singapore", "SG", "Asia", "English, Malay, Mandarin, Tamil"),
    SLOVAKIA("Slovakia", "SK", "Europe", "Slovak"),
    SLOVENIA("Slovenia", "SI", "Europe", "Slovenian"),
    SOLOMON_ISLANDS("Solomon Islands", "SB", "Oceania", "English"),
    SOMALIA("Somalia", "SO", "Africa", "Somali, Arabic"),
    SOUTH_AFRICA("South Africa", "ZA", "Africa", "Zulu, Xhosa, Afrikaans, English"),
    SOUTH_SUDAN("South Sudan", "SS", "Africa", "English"),
    SPAIN("Spain", "ES", "Europe", "Spanish"),
    SRI_LANKA("Sri Lanka", "LK", "Asia", "Sinhala, Tamil"),
    SUDAN("Sudan", "SD", "Africa", "Arabic, English"),
    SURINAME("Suriname", "SR", "South America", "Dutch"),
    SWEDEN("Sweden", "SE", "Europe", "Swedish"),
    SWITZERLAND("Switzerland", "CH", "Europe", "German, French, Italian, Romansh"),
    SYRIAN_ARAB_REPUBLIC("Syrian Arab Republic", "SY", "Asia", "Arabic"),
    TAJIKISTAN("Tajikistan", "TJ", "Asia", "Tajik"),
    TANZANIA_UNITED_REPUBLIC_OF("Tanzania, United Republic of", "TZ", "Africa", "Swahili, English"),
    THAILAND("Thailand", "TH", "Asia", "Thai"),
    TIMOR_LESTE("Timor-Leste", "TL", "Asia", "Tetum, Portuguese"),
    TOGO("Togo", "TG", "Africa", "French"),
    TONGA("Tonga", "TO", "Oceania", "Tongan, English"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "TT", "North America", "English"),
    TUNISIA("Tunisia", "TN", "Africa", "Arabic"),
    TURKEY("Turkey", "TR", "Asia", "Turkish"),
    TURKMENISTAN("Turkmenistan", "TM", "Asia", "Turkmen"),
    TUVALU("Tuvalu", "TV", "Oceania", "Tuvaluan, English"),
    UGANDA("Uganda", "UG", "Africa", "English, Swahili"),
    UKRAINE("Ukraine", "UA", "Europe", "Ukrainian"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "AE", "Asia", "Arabic"),
    UNITED_KINGDOM("United Kingdom", "GB", "Europe", "English"),
    UNITED_STATES("United States", "US", "North America", "English"),
    URUGUAY("Uruguay", "UY", "South America", "Spanish"),
    UZBEKISTAN("Uzbekistan", "UZ", "Asia", "Uzbek, Russian"),
    VANUATU("Vanuatu", "VU", "Oceania", "Bislama, English, French"),
    VENEZUELA_BOLIVARIAN_REPUBLIC_OF("Venezuela (Bolivarian Republic of)", "VE", "South America", "Spanish"),
    VIET_NAM("Viet Nam", "VN", "Asia", "Vietnamese"),
    YEMEN("Yemen", "YE", "Asia", "Arabic"),
    ZAMBIA("Zambia", "ZM", "Africa", "English"),
    ZIMBABWE("Zimbabwe", "ZW", "Africa", "English");

    // Constructor and getters
    private final String name;
    private final String code;
    private final String continent;
    private final String language;

    Country(String name, String code, String continent, String language) {
        this.name = name;
        this.code = code;
        this.continent = continent;
        this.language = language;
    }

    public String getName() {
        return name;
    }

    public String getCode() {
        return code;
    }

    public String getContinent() {
        return continent;
    }

    public String getLanguage() {
        return language;
    }
}
